ENT-4579: overriding chunk size in SAP
edx/edx-enterprise pull request #1291
Opened 2021-07-02 13:01 UTC by kiram15

**Merge checklist:**
- [x] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-platform doesn't install it
    - `test-master.in` if edx-platform pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [x] `make static` has been run to update webpack bundling if any static content was updated
- [x] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command through an lms shell.
        - It would be `./manage.py lms makemigrations` in the shell.
- [ ] [Version](https://github.com/edx/edx-enterprise/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/edx/edx-enterprise/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/edx-enterprise/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub Actions](https://github.com/edx/edx-enterprise/actions), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-platform](https://github.com/edx/edx-platform) to upgrade dependencies (including edx-enterprise)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
    - Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.

2021-07-02 18:24 UTC, alex-sheehan-edx approved these changes
Assuming you've tested locally, LGTM 👍

2021-07-07 15:18 UTC, taliaedX reviewed
It looks good. There is one change that I mention that will fix the test currently failing and I think this might be the point where we get you setup locally with integrated channels also since the rest of the sprint is also integrated channels. There is an office hours on Friday apparently, but anyone on the team (everybody except Lael worked on integrated channels 😂 ) can walk you through setup earlier if you'd prefer.

2021-07-07 20:55 UTC, taliaedX commented on integrated_channels/cornerstone/migrations/0007_auto_20210707_1258.py
> +            model_name='cornerstoneenterprisecustomerconfiguration',
Oooo no, no no let's not do this.

2021-07-07 21:00 UTC, taliaedX requested changes
I am blocking this PR to prevent this from even accidentally merging.

There are some unknowns in the behaviour modification of Degreed and Cornerstone and any others that aren't explicitly called out in the tickets. Even when called out in the tickets, we want to test to verify they all work. That's a lot of integrations to verify and for no discernible reason. Cornerstone is particularly uncertain to me. Let's just limit this to the scope of the tickets for now unless we explicitly are told the other integrations are also failing on large chunks.

2021-07-07 21:02 UTC, taliaedX commented on integrated_channels/integrated_channel/models.py
> +        default=1,
ie delete the `transmission_chunk_size` definitions from the individual models.
And for Degreed & Cornerstone and any others I didn't catch in this batch of commits, add `transmission_chunk_size = models.IntegerField(default=500)` to the enterprise customer configuration.

2021-07-08 00:21 UTC, kiram15 commented on integrated_channels/integrated_channel/models.py
> +        default=1,
I made these changes but thought the same thing, so I reached out to Rob Smith and he agreed with you so I'll revert it!

2021-07-08 15:52 UTC, taliaedX approved these changes

2021-07-08 15:53 UTC, taliaedX commented
Approved now. Don't forget to squash some more!

2021-07-08 15:59 UTC, merged