feat: Added support for django3.2
edx/edx-enterprise pull request #1320
Opened 2021-08-03 15:07 UTC by Jawayria

JIRA: https://openedx.atlassian.net/browse/BOM-2692

2021-08-09 14:57 UTC, awais786 commented on tests/test_models.py
> -class TestEnterpriseCustomerPluginConfiguration(unittest.TestCase):
These tests are for `EnterpriseCustomerPluginConfiguration` abstract model. Django has removed abstract model instantiating with this error `Instantiating an abstract model now raises TypeError.` in [django3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#miscellaneous). Django [PR](https://github.com/django/django/pull/13267) in which it is implemented.

So no need to test this functionality here.

2021-08-10 09:48 UTC, mzulqarnain1 requested changes
There's a warning in Django 2.2 tests
```
RemovedInDjango30Warning: Remove the context parameter from MultiEmailField.from_db_value(). Support for it will be removed in Django 3.0.
```
Please fix that too.

2021-08-10 09:48 UTC, mzulqarnain1 commented on tests/test_migrations.py
> +from six import StringIO
You can use `from io import StringIO` instead.

2021-09-07 10:10 UTC, awais786 approved these changes

2021-09-07 10:26 UTC, mzulqarnain1 approved these changes

2021-09-07 14:40 UTC, merged