fix: allowing records to be cross catalogs
edx/edx-enterprise pull request #1397
Opened 2021-11-02 15:41 UTC by alex-sheehan-edx

[Jira](https://openedx.atlassian.net/browse/ENT-5097)

A create request may be made for a piece of content that already exists for a customer under a different catalog. Therefore we need to check if a content record exists under another catalog before we attempt to create one. 

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-platform doesn't install it
    - `test-master.in` if edx-platform pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command through an lms shell.
        - It would be `./manage.py lms makemigrations` in the shell.
- [ ] [Version](https://github.com/edx/edx-enterprise/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/edx/edx-enterprise/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/edx-enterprise/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub Actions](https://github.com/edx/edx-enterprise/actions), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-platform](https://github.com/edx/edx-platform) to upgrade dependencies (including edx-enterprise)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
    - Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.

2021-11-02 15:54 UTC, binodpant commented on integrated_channels/integrated_channel/transmitters/content_metadata.py
> +                    past_transmission.save()
ah so no more bulk_update, just a per item update here replaces that right?

2021-11-02 15:55 UTC, binodpant commented on tests/test_integrated_channels/test_integrated_channel/test_transmitters/test_content_metadata.py
> +        import pdb;
remove debug calls

2021-11-02 16:01 UTC, binodpant requested changes

2021-11-02 16:04 UTC, binodpant commented on integrated_channels/integrated_channel/transmitters/content_metadata.py
> +            ).first()
I would also find it useful to have the docstring for this method quickly explain what it does and the 3 cases it handles and what it does in each case, just briefly is fine

2021-11-02 16:05 UTC, binodpant commented on integrated_channels/integrated_channel/transmitters/content_metadata.py
> +            ).first()
mainly think it's useful now since the method is no longer as simple as it used to be, but more accurate!

2021-11-02 19:05 UTC, alex-sheehan-edx commented on integrated_channels/integrated_channel/transmitters/content_metadata.py
>                      f'Found previously deleted content record while creating record for course: {content_id}'
transmissions don't have UUID's 😞 + the pairing of customer and content ID is unique so is in a way the identifying pair. I could log the ID but I just feel like it's not necessary.

2021-11-02 19:06 UTC, alex-sheehan-edx commented on integrated_channels/integrated_channel/transmitters/content_metadata.py
>                      f'Found previously deleted content record while creating record for course: {content_id}'
but I will indicate the intentions of the process for what it will do to the record (ie reactivate)

2021-11-03 14:11 UTC, binodpant approved these changes
wohoo!

2021-11-04 19:11 UTC, merged